export namespace WcdEnums {
  export module Country {
    export enum CountryTwoLetterCode {
      Afghanistan = "AF",
      AlandIslands = "AX",
      Albania = "AL",
      Algeria = "DZ",
      AmericanSamoa = "AS",
      Andorra = "AD",
      Angola = "AO",
      Anguilla = "AI",
      Antarctica = "AQ",
      AntiguaAndBarbuda = "AG",
      Argentina = "AR",
      Armenia = "AM",
      Aruba = "AW",
      Australia = "AU",
      Austria = "AT",
      Azerbaijan = "AZ",
      Bahamas = "BS",
      Bahrain = "BH",
      Bangladesh = "BD",
      Barbados = "BB",
      Belarus = "BY",
      Belgium = "BE",
      Belize = "BZ",
      Benin = "BJ",
      Bermuda = "BM",
      Bhutan = "BT",
      Bolivia = "BO",
      BonaireSintEustatiusSaba = "BQ",
      BosniaAndHerzegovina = "BA",
      Botswana = "BW",
      BouvetIsland = "BV",
      Brazil = "BR",
      BritishIndianOceanTerritory = "IO",
      BruneiDarussalam = "BN",
      Bulgaria = "BG",
      BurkinaFaso = "BF",
      Burundi = "BI",
      Cambodia = "KH",
      Cameroon = "CM",
      Canada = "CA",
      CapeVerde = "CV",
      CaymanIslands = "KY",
      CentralAfricanRepublic = "CF",
      Chad = "TD",
      Chile = "CL",
      China = "CN",
      ChristmasIsland = "CX",
      CocosKeelingIslands = "CC",
      Colombia = "CO",
      Comoros = "KM",
      Congo = "CG",
      CongoDemocraticRepublic = "CD",
      CookIslands = "CK",
      CostaRica = "CR",
      CoteDIvoire = "CI",
      Croatia = "HR",
      Cuba = "CU",
      Curaçao = "CW",
      Cyprus = "CY",
      CzechRepublic = "CZ",
      Denmark = "DK",
      Djibouti = "DJ",
      Dominica = "DM",
      DominicanRepublic = "DO",
      Ecuador = "EC",
      Egypt = "EG",
      ElSalvador = "SV",
      EquatorialGuinea = "GQ",
      Eritrea = "ER",
      Estonia = "EE",
      Ethiopia = "ET",
      FalklandIslands = "FK",
      FaroeIslands = "FO",
      Fiji = "FJ",
      Finland = "FI",
      France = "FR",
      FrenchGuiana = "GF",
      FrenchPolynesia = "PF",
      FrenchSouthernTerritories = "TF",
      Gabon = "GA",
      Gambia = "GM",
      Georgia = "GE",
      Germany = "DE",
      Ghana = "GH",
      Gibraltar = "GI",
      Greece = "GR",
      Greenland = "GL",
      Grenada = "GD",
      Guadeloupe = "GP",
      Guam = "GU",
      Guatemala = "GT",
      Guernsey = "GG",
      Guinea = "GN",
      GuineaBissau = "GW",
      Guyana = "GY",
      Haiti = "HT",
      HeardIslandMcdonaldIslands = "HM",
      HolySeeVaticanCityState = "VA",
      Honduras = "HN",
      HongKong = "HK",
      Hungary = "HU",
      Iceland = "IS",
      India = "IN",
      Indonesia = "ID",
      Iran = "IR",
      Iraq = "IQ",
      Ireland = "IE",
      IsleOfMan = "IM",
      Israel = "IL",
      Italy = "IT",
      Jamaica = "JM",
      Japan = "JP",
      Jersey = "JE",
      Jordan = "JO",
      Kazakhstan = "KZ",
      Kenya = "KE",
      Kiribati = "KI",
      Korea = "KR",
      KoreaDemocraticPeoplesRepublic = "KP",
      Kuwait = "KW",
      Kyrgyzstan = "KG",
      LaoPeoplesDemocraticRepublic = "LA",
      Latvia = "LV",
      Lebanon = "LB",
      Lesotho = "LS",
      Liberia = "LR",
      LibyanArabJamahiriya = "LY",
      Liechtenstein = "LI",
      Lithuania = "LT",
      Luxembourg = "LU",
      Macao = "MO",
      Macedonia = "MK",
      Madagascar = "MG",
      Malawi = "MW",
      Malaysia = "MY",
      Maldives = "MV",
      Mali = "ML",
      Malta = "MT",
      MarshallIslands = "MH",
      Martinique = "MQ",
      Mauritania = "MR",
      Mauritius = "MU",
      Mayotte = "YT",
      Mexico = "MX",
      Micronesia = "FM",
      Moldova = "MD",
      Monaco = "MC",
      Mongolia = "MN",
      Montenegro = "ME",
      Montserrat = "MS",
      Morocco = "MA",
      Mozambique = "MZ",
      Myanmar = "MM",
      Namibia = "NA",
      Nauru = "NR",
      Nepal = "NP",
      Netherlands = "NL",
      NewCaledonia = "NC",
      NewZealand = "NZ",
      Nicaragua = "NI",
      Niger = "NE",
      Nigeria = "NG",
      Niue = "NU",
      NorfolkIsland = "NF",
      NorthernMarianaIslands = "MP",
      Norway = "NO",
      Oman = "OM",
      Pakistan = "PK",
      Palau = "PW",
      PalestinianTerritory = "PS",
      Panama = "PA",
      PapuaNewGuinea = "PG",
      Paraguay = "PY",
      Peru = "PE",
      Philippines = "PH",
      Pitcairn = "PN",
      Poland = "PL",
      Portugal = "PT",
      PuertoRico = "PR",
      Qatar = "QA",
      Reunion = "RE",
      Romania = "RO",
      RussianFederation = "RU",
      Rwanda = "RW",
      SaintBarthelemy = "BL",
      SaintHelena = "SH",
      SaintKittsAndNevis = "KN",
      SaintLucia = "LC",
      SaintMartin = "MF",
      SaintPierreAndMiquelon = "PM",
      SaintVincentAndGrenadines = "VC",
      Samoa = "WS",
      SanMarino = "SM",
      SaoTomeAndPrincipe = "ST",
      SaudiArabia = "SA",
      Senegal = "SN",
      Serbia = "RS",
      Seychelles = "SC",
      SierraLeone = "SL",
      Singapore = "SG",
      SintMaarten = "SX",
      Slovakia = "SK",
      Slovenia = "SI",
      SolomonIslands = "SB",
      Somalia = "SO",
      SouthAfrica = "ZA",
      SouthGeorgiaAndSandwichIsl = "GS",
      SouthSudan = "SS",
      Spain = "ES",
      SriLanka = "LK",
      Sudan = "SD",
      Suriname = "SR",
      SvalbardAndJanMayen = "SJ",
      Swaziland = "SZ",
      Sweden = "SE",
      Switzerland = "CH",
      SyrianArabRepublic = "SY",
      Taiwan = "TW",
      Tajikistan = "TJ",
      Tanzania = "TZ",
      Thailand = "TH",
      TimorLeste = "TL",
      Togo = "TG",
      Tokelau = "TK",
      Tonga = "TO",
      TrinidadAndTobago = "TT",
      Tunisia = "TN",
      Turkey = "TR",
      Turkmenistan = "TM",
      TurksAndCaicosIslands = "TC",
      Tuvalu = "TV",
      Uganda = "UG",
      Ukraine = "UA",
      UnitedArabEmirates = "AE",
      UnitedKingdom = "GB",
      UnitedStates = "US",
      UnitedStatesOutlyingIslands = "UM",
      Uruguay = "UY",
      Uzbekistan = "UZ",
      Vanuatu = "VU",
      Venezuela = "VE",
      Vietnam = "VN",
      VirginIslandsBritish = "VG",
      VirginIslandsUS = "VI",
      WallisAndFutuna = "WF",
      WesternSahara = "EH",
      Yemen = "YE",
      Zambia = "ZM",
      Zimbabwe = "ZW"
    }
  }
  export module DateTime {
    export enum DateFormat {
      "iso8601",
      "written"
    }
    export enum Preference {
      "date",
      "time12",
      "time24",
      "datetime24",
      "datetime12"
    }
    export enum DateTimeSeparator {
      "at",
      "comma",
      "none"
    }
    export enum Months {
      January = "January",
      February = "February",
      March = "March",
      April = "April",
      May = "May",
      June = "June",
      July = "July",
      August = "August",
      September = "September",
      October = "October",
      November = "November",
      December = "December"
    }
    export enum TimeZones {
      "Pacific/Midway",
      "Pacific/Niue",
      "Pacific/Pago_Pago",
      "America/Adak",
      "Pacific/Honolulu",
      "Pacific/Rarotonga",
      "Pacific/Tahiti",
      "Pacific/Marquesas",
      "America/Anchorage",
      "America/Juneau",
      "America/Metlakatla",
      "America/Nome",
      "America/Sitka",
      "America/Yakutat",
      "Pacific/Gambier",
      "America/Los_Angeles",
      "America/Tijuana",
      "America/Vancouver",
      "Pacific/Pitcairn",
      "America/Boise",
      "America/Cambridge_Bay",
      "America/Chihuahua",
      "America/Creston",
      "America/Dawson",
      "America/Dawson_Creek",
      "America/Denver",
      "America/Edmonton",
      "America/Fort_Nelson",
      "America/Hermosillo",
      "America/Inuvik",
      "America/Mazatlan",
      "America/Ojinaga",
      "America/Phoenix",
      "America/Whitehorse",
      "America/Yellowknife",
      "America/Bahia_Banderas",
      "America/Belize",
      "America/Chicago",
      "America/Costa_Rica",
      "America/El_Salvador",
      "America/Guatemala",
      "America/Indiana/Knox",
      "America/Indiana/Tell_City",
      "America/Managua",
      "America/Matamoros",
      "America/Menominee",
      "America/Merida",
      "America/Mexico_City",
      "America/Monterrey",
      "America/North_Dakota/Beulah",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/Rainy_River",
      "America/Rankin_Inlet",
      "America/Regina",
      "America/Resolute",
      "America/Swift_Current",
      "America/Tegucigalpa",
      "America/Winnipeg",
      "Pacific/Easter",
      "Pacific/Galapagos",
      "America/Atikokan",
      "America/Bogota",
      "America/Cancun",
      "America/Cayman",
      "America/Detroit",
      "America/Eirunepe",
      "America/Grand_Turk",
      "America/Guayaquil",
      "America/Havana",
      "America/Indiana/Indianapolis",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Iqaluit",
      "America/Jamaica",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/Lima",
      "America/Nassau",
      "America/New_York",
      "America/Nipigon",
      "America/Panama",
      "America/Pangnirtung",
      "America/Port-au-Prince",
      "America/Rio_Branco",
      "America/Thunder_Bay",
      "America/Toronto",
      "America/AnguillaSandy Hill",
      "America/Antigua",
      "America/Aruba",
      "America/Asuncion",
      "America/Barbados",
      "America/Blanc-Sablon",
      "America/Boa_Vista",
      "America/Campo_Grande",
      "America/Caracas",
      "America/Cuiaba",
      "America/Curacao",
      "America/Dominica",
      "America/Glace_Bay",
      "America/Goose_Bay",
      "America/Grenada",
      "America/Guadeloupe",
      "America/Guyana",
      "America/Halifax",
      "America/Kralendijk",
      "America/La_Paz",
      "America/Lower_Princes",
      "America/Manaus",
      "America/Marigot",
      "America/Martinique",
      "America/Moncton",
      "America/Montserrat",
      "America/Porto_Velho",
      "America/Port_of_Spain",
      "America/Puerto_Rico",
      "America/Santiago",
      "America/Santo_Domingo",
      "America/St_Barthelemy",
      "America/St_Kitts",
      "America/St_Lucia",
      "America/St_Thomas",
      "America/St_Vincent",
      "America/Thule",
      "America/Tortola",
      "Atlantic/Bermuda",
      "America/St_Johns",
      "America/Araguaina",
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Catamarca",
      "America/Argentina/Cordoba",
      "America/Argentina/Jujuy",
      "America/Argentina/La_Rioja",
      "America/Argentina/Mendoza",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Salta",
      "America/Argentina/San_Juan",
      "America/Argentina/San_Luis",
      "America/Argentina/Tucuman",
      "America/Argentina/Ushuaia",
      "America/Bahia",
      "America/Belem",
      "America/Cayenne",
      "America/Fortaleza",
      "America/Godthab",
      "America/Maceio",
      "America/Miquelon",
      "America/Montevideo",
      "America/Paramaribo",
      "America/Punta_Arenas",
      "America/Recife",
      "America/Santarem",
      "America/Sao_Paulo",
      "Antarctica/Palmer",
      "Antarctica/Rothera",
      "Atlantic/Stanley",
      "America/Noronha",
      "Atlantic/South_Georgia",
      "America/Scoresbysund",
      "Atlantic/Azores",
      "Atlantic/Cape_Verde",
      "Africa/Abidjan",
      "Africa/Accra",
      "Africa/Bamako",
      "Africa/Banjul",
      "Africa/Bissau",
      "Africa/Casablanca",
      "Africa/Conakry",
      "Africa/Dakar",
      "Africa/El_Aaiun",
      "Africa/Freetown",
      "Africa/Lome",
      "Africa/Monrovia",
      "Africa/Nouakchott",
      "Africa/Ouagadougou",
      "Africa/Sao_Tome",
      "America/Danmarkshavn",
      "Antarctica/Troll",
      "Atlantic/Canary",
      "Atlantic/Faroe",
      "Atlantic/Madeira",
      "Atlantic/Reykjavik",
      "Atlantic/St_Helena",
      "Europe/Dublin",
      "Europe/Guernsey",
      "Europe/Isle_of_Man",
      "Europe/Jersey",
      "Europe/Lisbon",
      "Europe/London",
      "Africa/Algiers",
      "Africa/Bangui",
      "Africa/Brazzaville",
      "Africa/Ceuta",
      "Africa/Douala",
      "Africa/Kinshasa",
      "Africa/Lagos",
      "Africa/Libreville",
      "Africa/Luanda",
      "Africa/Malabo",
      "Africa/Ndjamena",
      "Africa/Niamey",
      "Africa/Porto-Novo",
      "Africa/Tunis",
      "Africa/Windhoek",
      "Arctic/Longyearbyen",
      "Europe/Amsterdam",
      "Europe/Andorra",
      "Europe/Belgrade",
      "Europe/Berlin",
      "Europe/Bratislava",
      "Europe/Brussels",
      "Europe/Budapest",
      "Europe/Copenhagen",
      "Europe/Gibraltar",
      "Europe/Ljubljana",
      "Europe/Luxembourg",
      "Europe/Madrid",
      "Europe/Malta",
      "Europe/Monaco",
      "Europe/Oslo",
      "Europe/Paris",
      "Europe/Podgorica",
      "Europe/Prague",
      "Europe/Rome",
      "Europe/San_Marino",
      "Europe/Sarajevo",
      "Europe/Skopje",
      "Europe/Stockholm",
      "Europe/Tirane",
      "Europe/Vaduz",
      "Europe/Vatican",
      "Europe/Vienna",
      "Europe/Warsaw",
      "Europe/Zagreb",
      "Europe/Zurich",
      "Africa/Blantyre",
      "Africa/Bujumbura",
      "Africa/Cairo",
      "Africa/Gaborone",
      "Africa/Harare",
      "Africa/Johannesburg",
      "Africa/Juba",
      "Africa/Khartoum",
      "Africa/Kigali",
      "Africa/Lubumbashi",
      "Africa/Lusaka",
      "Africa/Maputo",
      "Africa/Maseru",
      "Africa/Mbabane",
      "Africa/Tripoli",
      "Asia/Amman",
      "Asia/Beirut",
      "Asia/Damascus",
      "Asia/Famagusta",
      "Asia/Gaza",
      "Asia/Hebron",
      "Asia/Jerusalem",
      "Asia/Nicosia",
      "Europe/Athens",
      "Europe/Bucharest",
      "Europe/Chisinau",
      "Europe/Helsinki",
      "Europe/Kaliningrad",
      "Europe/Kiev",
      "Europe/Mariehamn",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Uzhgorod",
      "Europe/Vilnius",
      "Europe/Zaporozhye",
      "Africa/Addis_Ababa",
      "Africa/Asmara",
      "Africa/Dar_es_Salaam",
      "Africa/Djibouti",
      "Africa/Kampala",
      "Africa/Mogadishu",
      "Africa/Nairobi",
      "Antarctica/Syowa",
      "Asia/Aden",
      "Asia/Baghdad",
      "Asia/Bahrain",
      "Asia/Kuwait",
      "Asia/Qatar",
      "Asia/Riyadh",
      "Europe/Istanbul",
      "Europe/Kirov",
      "Europe/Minsk",
      "Europe/Moscow",
      "Europe/Simferopol",
      "Europe/Volgograd",
      "Indian/Antananarivo",
      "Indian/Comoro",
      "Indian/Mayotte",
      "Asia/Tehran",
      "Asia/Baku",
      "Asia/Dubai",
      "Asia/Muscat",
      "Asia/Tbilisi",
      "Asia/Yerevan",
      "Europe/Astrakhan",
      "Europe/Samara",
      "Europe/Saratov",
      "Europe/Ulyanovsk",
      "Indian/Mahe",
      "Indian/Mauritius",
      "Indian/Reunion",
      "Asia/Kabul",
      "Antarctica/Mawson",
      "Asia/Aqtau",
      "Asia/Aqtobe",
      "Asia/Ashgabat",
      "Asia/Atyrau",
      "Asia/Dushanbe",
      "Asia/Karachi",
      "Asia/Oral",
      "Asia/Qyzylorda",
      "Asia/Samarkand",
      "Asia/Tashkent",
      "Asia/Yekaterinburg",
      "Indian/Kerguelen",
      "Indian/Maldives",
      "Asia/Colombo",
      "Asia/Kolkata",
      "Asia/Kathmandu",
      "Antarctica/Vostok",
      "Asia/Almaty",
      "Asia/Bishkek",
      "Asia/Dhaka",
      "Asia/Omsk",
      "Asia/Qostanay",
      "Asia/Thimphu",
      "Asia/Urumqi",
      "Indian/Chagos",
      "Asia/Yangon",
      "Indian/Cocos",
      "Antarctica/Davis",
      "Asia/Bangkok",
      "Asia/Barnaul",
      "Asia/Hovd",
      "Asia/Ho_Chi_Minh",
      "Asia/Jakarta",
      "Asia/Krasnoyarsk",
      "Asia/Novokuznetsk",
      "Asia/Novosibirsk",
      "Asia/Phnom_Penh",
      "Asia/Pontianak",
      "Asia/Tomsk",
      "Asia/Vientiane",
      "Indian/Christmas",
      "Asia/Brunei",
      "Asia/Choibalsan",
      "Asia/Hong_Kong",
      "Asia/Irkutsk",
      "Asia/Kuala_Lumpur",
      "Asia/Kuching",
      "Asia/Macau",
      "Asia/Makassar",
      "Asia/Manila",
      "Asia/Shanghai",
      "Asia/Singapore",
      "Asia/Taipei",
      "Asia/Ulaanbaatar",
      "Australia/Perth",
      "Australia/Eucla",
      "Asia/Chita",
      "Asia/Dili",
      "Asia/Jayapura",
      "Asia/Khandyga",
      "Asia/Pyongyang",
      "Asia/Seoul",
      "Asia/Tokyo",
      "Asia/Yakutsk",
      "Pacific/Palau",
      "Australia/Adelaide",
      "Australia/Broken_Hill",
      "Australia/Darwin",
      "Antarctica/DumontDUrville",
      "Antarctica/Macquarie",
      "Asia/Ust-Nera",
      "Asia/Vladivostok",
      "Australia/Brisbane",
      "Australia/Currie",
      "Australia/Hobart",
      "Australia/Lindeman",
      "Australia/Melbourne",
      "Australia/Sydney",
      "Pacific/Chuuk",
      "Pacific/GuamVillage",
      "Pacific/Port_Moresby",
      "Pacific/Saipan",
      "Australia/Lord_Howe",
      "Antarctica/Casey",
      "Asia/Magadan",
      "Asia/Sakhalin",
      "Asia/Srednekolymsk",
      "Pacific/Bougainville",
      "Pacific/Efate",
      "Pacific/Guadalcanal",
      "Pacific/Kosrae",
      "Pacific/Norfolk",
      "Pacific/Noumea",
      "Pacific/Pohnpei",
      "Antarctica/McMurdo",
      "Asia/Anadyr",
      "Asia/Kamchatka",
      "Pacific/Auckland",
      "Pacific/Fiji",
      "Pacific/Funafuti",
      "Pacific/Kwajalein",
      "Pacific/Majuro",
      "Pacific/Nauru",
      "Pacific/Tarawa",
      "Pacific/Wake",
      "Pacific/Wallis",
      "Pacific/Chatham",
      "Pacific/Apia",
      "Pacific/Enderbury",
      "Pacific/Fakaofo",
      "Pacific/Tongatapu",
      "Pacific/Kiritimati"
    }
  }
  export module Network {
    export enum HttpStatus {
      CONTINUE = 100,
      SWITCHING_PROTOCOLS = 101,
      PROCESSING = 102,
      OK = 200,
      CREATED = 201,
      ACCEPTED = 202,
      NON_AUTHORITATIVE_INFORMATION = 203,
      NO_CONTENT = 204,
      RESET_CONTENT = 205,
      PARTIAL_CONTENT = 206,
      AMBIGUOUS = 300,
      MOVED_PERMANENTLY = 301,
      FOUND = 302,
      SEE_OTHER = 303,
      NOT_MODIFIED = 304,
      TEMPORARY_REDIRECT = 307,
      PERMANENT_REDIRECT = 308,
      BAD_REQUEST = 400,
      UNAUTHORIZED = 401,
      PAYMENT_REQUIRED = 402,
      FORBIDDEN = 403,
      NOT_FOUND = 404,
      METHOD_NOT_ALLOWED = 405,
      NOT_ACCEPTABLE = 406,
      PROXY_AUTHENTICATION_REQUIRED = 407,
      REQUEST_TIMEOUT = 408,
      CONFLICT = 409,
      GONE = 410,
      LENGTH_REQUIRED = 411,
      PRECONDITION_FAILED = 412,
      PAYLOAD_TOO_LARGE = 413,
      URI_TOO_LONG = 414,
      UNSUPPORTED_MEDIA_TYPE = 415,
      REQUESTED_RANGE_NOT_SATISFIABLE = 416,
      EXPECTATION_FAILED = 417,
      I_AM_A_TEAPOT = 418,
      UNPROCESSABLE_ENTITY = 422,
      TOO_MANY_REQUESTS = 429,
      INTERNAL_SERVER_ERROR = 500,
      NOT_IMPLEMENTED = 501,
      BAD_GATEWAY = 502,
      SERVICE_UNAVAILABLE = 503,
      GATEWAY_TIMEOUT = 504,
      HTTP_VERSION_NOT_SUPPORTED = 505
    }
    export enum RequestMethod {
      GET,
      POST,
      PUT,
      DELETE,
      PATCH,
      ALL,
      OPTIONS,
      LINK,
      UNLINK,
      HEAD
    }
    export enum RouteParamtypes {
      REQUEST,
      RESPONSE,
      NEXT,
      BODY,
      QUERY,
      PARAM,
      HEADERS,
      SESSION,
      FILE,
      FILES
    }
  }
  export module System {
    export enum ShutdownSignal {
      SIGHUP = "SIGHUP",
      SIGINT = "SIGINT",
      SIGQUIT = "SIGQUIT",
      SIGILL = "SIGILL",
      SIGTRAP = "SIGTRAP",
      SIGABRT = "SIGABRT",
      SIGBUS = "SIGBUS",
      SIGFPE = "SIGFPE",
      SIGSEGV = "SIGSEGV",
      SIGUSR2 = "SIGUSR2",
      SIGTERM = "SIGTERM"
    }
  }
}

export default WcdEnums;
